name: CalcX master build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master codebase
        uses: actions/checkout@v2.0.0
        with:
          repository: selimser/CalcX
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.x
        
        
      - name: Directory Scan
        run: ls -l
       
      - name: Build Project
        run: dotnet build Calcx.sln --configuration Release
